repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: python-format
        name: python-format
        types_or: [python]
        entry: make format
        language: system
        pass_filenames: false
      - id: python-typecheck
        name: python-typecheck
        types_or: [python]
        entry: make typecheck
        language: system
        pass_filenames: false
      - id: js-prettier
        name: js-prettier
        types_or: [javascript, jsx, ts, tsx, css, json, markdown]
        entry: npm run prettier
        language: system
      - id: js-lint
        name: js-lint
        types_or: [ts, tsx]
        entry: npm run lint-fix
        language: system
        pass_filenames: false
      - id: js-typecheck
        name: js-typecheck
        types_or: [ts, tsx]
        entry: npm run typecheck
        language: system
        pass_filenames: false
      - id: python-generate-ts
        name: python-generate-ts
        types_or: [python]
        entry: make typescript-models
        language: system
        pass_filenames: false
