# this is not the used for the python package "fastui",
# for that see packages/python-fastui/pyproject.toml

[tool.ruff]
line-length = 120
lint.extend-select = ["Q", "RUF100", "UP", "I"]
lint.flake8-quotes = {inline-quotes = "single", multiline-quotes = "double"}
format.quote-style="single"
target-version = "py38"

[tool.pyright]
include = ["src/python-fastui/fastui"]

[tool.pytest.ini_options]
testpaths = [
    "src/python-fastui/tests",
    "demo/tests.py",
]
xfail_strict = true
filterwarnings = ["error"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["src/python-fastui/fastui"]
omit = [
    "src/python-fastui/fastui/__main__.py",
    "src/python-fastui/fastui/generate_typescript.py",
]

[tool.coverage.report]
precision = 2
exclude_lines = [
    'pragma: no cover',
    'raise NotImplementedError',
    'if TYPE_CHECKING:',
    'if typing.TYPE_CHECKING:',
    '@overload',
    '@typing.overload',
    '\(Protocol\):$',
]
